In [66]:
pip install pandas

Requirement already satisfied: pandas in c:\users\gabriela\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\gabriela\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gabriela\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gabriela\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gabriela\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\gabriela\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

Cargar base de datos

In [67]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Gabyy14-nt/PROYECTO_CDD/refs/heads/main/df_sucio.csv')
df

,User_ID,Age,Gender,Technology_Usage_Hours,Social_Media_Usage_Hours,Gaming_Hours,Screen_Time_Hours,Mental_Health_Status,Stress_Level,Sleep_Hours,Physical_Activity_Hours,Support_Systems_Access,Work_Environment_Impact,Online_Support_Usage
0,USER-00001,23.0,Female,6.57,6.0,0.68,12.36,Good,Low,8.01,6.71,No,Negative,NaN
1,USER-00002,21.0,Male,3.01,2.57,3.74,7.61,Poor,High,7.28,5.88,Yes,Positive,NaN
2,USER-00003,51.0,Male,3.04,6.14,1.26,3.16,Fair,High,8.04,9.81,No,Negative,NaN
3,USER-00004,25.0,Female,3.84,4.48,2.59,13.08,Excellent,Medium,5.62,5.28,Yes,Negative,NaN
4,USER-00005,53.0,Male,1.2,0.56,0.29,12.63,Good,Low,5.55,4.0,No,Positive,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12524,USER-06709,24.0,Female,5.08,1.58,1.13,6.58,Poor,Low,7.74,0.04,Yes,Negative,NaN
12525,USER-09996,42.0,Male,7.05,0.41,0.53,13.90,invalid,Medium,7.37,5.02,Yes,NaN,NaN
12526,USER-02814,36.0,Male,4.42,0.08,2.20,10.48,Good,Medium,6.91,invalid,No,Positive,NaN
12527,USER-06331,35.0,Female,4.28,0.9,4.90,NaN,Fair,High,8.51,0.41,Yes,Neutral,NaN
12528,USER-07333,50.0,Female,11.85,0.4,1.70,6.21,Good,High,4.82,0.65,Yes,Negative,NaN

In [68]:
df.describe()

       Gaming_Hours  Screen_Time_Hours  Online_Support_Usage
count  12164.000000       12164.000000                   0.0
mean       2.520382           7.976828                   NaN
std        1.450498           4.050130                   NaN
min        0.000000           1.000000                   NaN
25%        1.260000           4.520000                   NaN
50%        2.520000           7.920000                   NaN
75%        3.810000          11.510000                   NaN
max        5.000000          15.000000                   NaN

In [69]:
df.columns

Index(['User_ID', 'Age', 'Gender', 'Technology_Usage_Hours',
       'Social_Media_Usage_Hours', 'Gaming_Hours', 'Screen_Time_Hours',
       'Mental_Health_Status', 'Stress_Level', 'Sleep_Hours',
       'Physical_Activity_Hours', 'Support_Systems_Access',
       'Work_Environment_Impact', 'Online_Support_Usage'],
      dtype='object')

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12529 entries, 0 to 12528
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   User_ID                   12417 non-null  object
 1   Age                       12403 non-null  object
 2   Gender                    12421 non-null  object
 3   Technology_Usage_Hours    12405 non-null  object
 4   Social_Media_Usage_Hours  12406 non-null  object
 5   Gaming_Hours              12164 non-null  float64
 6   Screen_Time_Hours         12164 non-null  float64
 7   Mental_Health_Status      12412 non-null  object
 8   Stress_Level              12397 non-null  object
 9   Sleep_Hours               12388 non-null  object
 10  Physical_Activity_Hours   12405 non-null  object
 11  Support_Systems_Access    12393 non-null  object
 12  Work_Environment_Impact   12378 non-null  object
 13  Online_Support_Usage      0 non-null      float64
dtypes: float64(3), object(11)
memory usage: 1.3+ MB

In [71]:
df.isnull().sum()

User_ID                       112
Age                           126
Gender                        108
Technology_Usage_Hours        124
Social_Media_Usage_Hours      123
Gaming_Hours                  365
Screen_Time_Hours             365
Mental_Health_Status          117
Stress_Level                  132
Sleep_Hours                   141
Physical_Activity_Hours       124
Support_Systems_Access        136
Work_Environment_Impact       151
Online_Support_Usage        12529
dtype: int64

In [72]:
#Elimino culumna Online_Support_Usage, todos sus datos son NaN
df=df.drop(columns=['Online_Support_Usage'])
df

,User_ID,Age,Gender,Technology_Usage_Hours,Social_Media_Usage_Hours,Gaming_Hours,Screen_Time_Hours,Mental_Health_Status,Stress_Level,Sleep_Hours,Physical_Activity_Hours,Support_Systems_Access,Work_Environment_Impact
0,USER-00001,23.0,Female,6.57,6.0,0.68,12.36,Good,Low,8.01,6.71,No,Negative
1,USER-00002,21.0,Male,3.01,2.57,3.74,7.61,Poor,High,7.28,5.88,Yes,Positive
2,USER-00003,51.0,Male,3.04,6.14,1.26,3.16,Fair,High,8.04,9.81,No,Negative
3,USER-00004,25.0,Female,3.84,4.48,2.59,13.08,Excellent,Medium,5.62,5.28,Yes,Negative
4,USER-00005,53.0,Male,1.2,0.56,0.29,12.63,Good,Low,5.55,4.0,No,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12524,USER-06709,24.0,Female,5.08,1.58,1.13,6.58,Poor,Low,7.74,0.04,Yes,Negative
12525,USER-09996,42.0,Male,7.05,0.41,0.53,13.90,invalid,Medium,7.37,5.02,Yes,NaN
12526,USER-02814,36.0,Male,4.42,0.08,2.20,10.48,Good,Medium,6.91,invalid,No,Positive
12527,USER-06331,35.0,Female,4.28,0.9,4.90,NaN,Fair,High,8.51,0.41,Yes,Neutral
12528,USER-07333,50.0,Female,11.85,0.4,1.70,6.21,Good,High,4.82,0.65,Yes,Negative

In [73]:
#Buscar duplicados
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
12524     True
12525    False
12526     True
12527    False
12528     True
Length: 12529, dtype: bool

In [74]:
#Eliminar duplicados
df=df.drop_duplicates()
df

,User_ID,Age,Gender,Technology_Usage_Hours,Social_Media_Usage_Hours,Gaming_Hours,Screen_Time_Hours,Mental_Health_Status,Stress_Level,Sleep_Hours,Physical_Activity_Hours,Support_Systems_Access,Work_Environment_Impact
0,USER-00001,23.0,Female,6.57,6.0,0.68,12.36,Good,Low,8.01,6.71,No,Negative
1,USER-00002,21.0,Male,3.01,2.57,3.74,7.61,Poor,High,7.28,5.88,Yes,Positive
2,USER-00003,51.0,Male,3.04,6.14,1.26,3.16,Fair,High,8.04,9.81,No,Negative
3,USER-00004,25.0,Female,3.84,4.48,2.59,13.08,Excellent,Medium,5.62,5.28,Yes,Negative
4,USER-00005,53.0,Male,1.2,0.56,0.29,12.63,Good,Low,5.55,4.0,No,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12519,USER-01052,36.0,Other,8.97,3.02,4.05,6.52,Good,Medium,5.4,8.44,Yes,Positive
12520,USER-05760,46.0,Male,invalid,2.2,4.71,13.31,Excellent,Medium,6.51,7.03,No,Neutral
12523,USER-02010,25.0,Other,3.82,3.71,3.61,6.57,Poor,Low,4.78,2.29,Yes,Negative
12525,USER-09996,42.0,Male,7.05,0.41,0.53,13.90,invalid,Medium,7.37,5.02,Yes,NaN
12527,USER-06331,35.0,Female,4.28,0.9,4.90,NaN,Fair,High,8.51,0.41,Yes,Neutral

Renombrar nombres de columnas.

In [75]:
df2 = df.rename(columns= {'User_ID': 'Usuario', 'Age': 'Edad', 'Gender': 'GÃ©nero', 'Technology_Usage_Hours': 'Horas_de_uso _de_la_tecnologÃ­a', 'Social_Media_Usage_Hours': 'Horas_de_uso_de_las_redes_sociales', 'Gaming_Hours': 'Horas_de_juego', 'Screen_Time_Hours': 'Horas_de_tiempo_en_pantalla', 'Mental_Health_Status': 'Estado_de_salud_mental', 'Stress_Level': 'Nivel_de_estrÃ©s', 'Sleep_Hours': 'Horas_de_sueÃ±o', 'Physical_Activity_Hours': 'Horas_de_actividad_fÃ­sica', 'Support_Systems_Access': 'Acceso_a_sistemas_de_soporte', 'Work_Environment_Impact': 'Impacto_en_el_entorno_laboral'})
df2

,Usuario,Edad,GÃ©nero,Horas_de_uso _de_la_tecnologÃ­a,Horas_de_uso_de_las_redes_sociales,Horas_de_juego,Horas_de_tiempo_en_pantalla,Estado_de_salud_mental,Nivel_de_estrÃ©s,Horas_de_sueÃ±o,Horas_de_actividad_fÃ­sica,Acceso_a_sistemas_de_soporte,Impacto_en_el_entorno_laboral
0,USER-00001,23.0,Female,6.57,6.0,0.68,12.36,Good,Low,8.01,6.71,No,Negative
1,USER-00002,21.0,Male,3.01,2.57,3.74,7.61,Poor,High,7.28,5.88,Yes,Positive
2,USER-00003,51.0,Male,3.04,6.14,1.26,3.16,Fair,High,8.04,9.81,No,Negative
3,USER-00004,25.0,Female,3.84,4.48,2.59,13.08,Excellent,Medium,5.62,5.28,Yes,Negative
4,USER-00005,53.0,Male,1.2,0.56,0.29,12.63,Good,Low,5.55,4.0,No,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12519,USER-01052,36.0,Other,8.97,3.02,4.05,6.52,Good,Medium,5.4,8.44,Yes,Positive
12520,USER-05760,46.0,Male,invalid,2.2,4.71,13.31,Excellent,Medium,6.51,7.03,No,Neutral
12523,USER-02010,25.0,Other,3.82,3.71,3.61,6.57,Poor,Low,4.78,2.29,Yes,Negative
12525,USER-09996,42.0,Male,7.05,0.41,0.53,13.90,invalid,Medium,7.37,5.02,Yes,NaN
12527,USER-06331,35.0,Female,4.28,0.9,4.90,NaN,Fair,High,8.51,0.41,Yes,Neutral

Renombrar datos de columnas.

In [76]:
#GÃ©nero
gen={
    'Female': 'Mujer',
    'Male': 'Hombre',
    'Other': 'Otro'
}
#Salud mental
sm={
    'Excellent': 'Excelente',
    'Good': 'Buena',
    'Fair': 'Neutral',
    'Poor': 'Mala'
}
#Nivel de estrÃ©s
ne={
    'Low': 'Bajo',
    'Medium': 'Medio',
    'High': 'Alto'
}
#Acceso a sistemas de soporte
ss={
    'Yes': 'Si'
}
#Impacto en el entorno laboral
el={
    'Negative': 'Negativo',
    'Positive': 'Positivo'
}

In [77]:
df2['GÃ©nero']=df2['GÃ©nero'].replace(gen)
df2['Estado_de_salud_mental']=df2['Estado_de_salud_mental'].replace(sm)
df2['Nivel_de_estrÃ©s']=df2['Nivel_de_estrÃ©s'].replace(ne)
df2['Acceso_a_sistemas_de_soporte']=df2['Acceso_a_sistemas_de_soporte'].replace(ss)
df2['Impacto_en_el_entorno_laboral']=df2['Impacto_en_el_entorno_laboral'].replace(el)
df2

,Usuario,Edad,GÃ©nero,Horas_de_uso _de_la_tecnologÃ­a,Horas_de_uso_de_las_redes_sociales,Horas_de_juego,Horas_de_tiempo_en_pantalla,Estado_de_salud_mental,Nivel_de_estrÃ©s,Horas_de_sueÃ±o,Horas_de_actividad_fÃ­sica,Acceso_a_sistemas_de_soporte,Impacto_en_el_entorno_laboral
0,USER-00001,23.0,Mujer,6.57,6.0,0.68,12.36,Buena,Bajo,8.01,6.71,No,Negativo
1,USER-00002,21.0,Hombre,3.01,2.57,3.74,7.61,Mala,Alto,7.28,5.88,Si,Positivo
2,USER-00003,51.0,Hombre,3.04,6.14,1.26,3.16,Neutral,Alto,8.04,9.81,No,Negativo
3,USER-00004,25.0,Mujer,3.84,4.48,2.59,13.08,Excelente,Medio,5.62,5.28,Si,Negativo
4,USER-00005,53.0,Hombre,1.2,0.56,0.29,12.63,Buena,Bajo,5.55,4.0,No,Positivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12519,USER-01052,36.0,Otro,8.97,3.02,4.05,6.52,Buena,Medio,5.4,8.44,Si,Positivo
12520,USER-05760,46.0,Hombre,invalid,2.2,4.71,13.31,Excelente,Medio,6.51,7.03,No,Neutral
12523,USER-02010,25.0,Otro,3.82,3.71,3.61,6.57,Mala,Bajo,4.78,2.29,Si,Negativo
12525,USER-09996,42.0,Hombre,7.05,0.41,0.53,13.90,invalid,Medio,7.37,5.02,Si,NaN
12527,USER-06331,35.0,Mujer,4.28,0.9,4.90,NaN,Neutral,Alto,8.51,0.41,Si,Neutral

Eliminamos los invalid.

In [78]:
#Contamos los invalid 
lista_col=df2.columns
for i in lista_col:
    print(f"En la columna {i} los invalid son: {df2[df2[i] == 'invalid'].shape[0]}")

En la columna Usuario los invalid son: 232
En la columna Edad los invalid son: 249
En la columna GÃ©nero los invalid son: 264
En la columna Horas_de_uso _de_la_tecnologÃ­a los invalid son: 249
En la columna Horas_de_uso_de_las_redes_sociales los invalid son: 253
En la columna Horas_de_juego los invalid son: 0
En la columna Horas_de_tiempo_en_pantalla los invalid son: 0
En la columna Estado_de_salud_mental los invalid son: 246
En la columna Nivel_de_estrÃ©s los invalid son: 257
En la columna Horas_de_sueÃ±o los invalid son: 251
En la columna Horas_de_actividad_fÃ­sica los invalid son: 272
En la columna Acceso_a_sistemas_de_soporte los invalid son: 237
En la columna Impacto_en_el_entorno_laboral los invalid son: 232

In [79]:
#Eliminamos los invalid
for i in lista_col:
    df2=df2[df2[i] != 'invalid']
df2

,Usuario,Edad,GÃ©nero,Horas_de_uso _de_la_tecnologÃ­a,Horas_de_uso_de_las_redes_sociales,Horas_de_juego,Horas_de_tiempo_en_pantalla,Estado_de_salud_mental,Nivel_de_estrÃ©s,Horas_de_sueÃ±o,Horas_de_actividad_fÃ­sica,Acceso_a_sistemas_de_soporte,Impacto_en_el_entorno_laboral
0,USER-00001,23.0,Mujer,6.57,6.0,0.68,12.36,Buena,Bajo,8.01,6.71,No,Negativo
1,USER-00002,21.0,Hombre,3.01,2.57,3.74,7.61,Mala,Alto,7.28,5.88,Si,Positivo
2,USER-00003,51.0,Hombre,3.04,6.14,1.26,3.16,Neutral,Alto,8.04,9.81,No,Negativo
3,USER-00004,25.0,Mujer,3.84,4.48,2.59,13.08,Excelente,Medio,5.62,5.28,Si,Negativo
4,USER-00005,53.0,Hombre,1.2,0.56,0.29,12.63,Buena,Bajo,5.55,4.0,No,Positivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12513,USER-07314,30.0,Otro,3.13,5.66,0.11,1.74,Buena,Bajo,4.05,0.47,Si,Neutral
12515,USER-09553,53.0,Mujer,10.32,7.35,4.58,NaN,Neutral,Bajo,7.3,5.92,No,Negativo
12519,USER-01052,36.0,Otro,8.97,3.02,4.05,6.52,Buena,Medio,5.4,8.44,Si,Positivo
12523,USER-02010,25.0,Otro,3.82,3.71,3.61,6.57,Mala,Bajo,4.78,2.29,Si,Negativo
12527,USER-06331,35.0,Mujer,4.28,0.9,4.90,NaN,Neutral,Alto,8.51,0.41,Si,Neutral

In [80]:
lista_col=df2.columns
for i in lista_col:
    print(f"En la columna {i} los invalid son: {df2[df2[i] == 'invalid'].shape[0]}")

En la columna Usuario los invalid son: 0
En la columna Edad los invalid son: 0
En la columna GÃ©nero los invalid son: 0
En la columna Horas_de_uso _de_la_tecnologÃ­a los invalid son: 0
En la columna Horas_de_uso_de_las_redes_sociales los invalid son: 0
En la columna Horas_de_juego los invalid son: 0
En la columna Horas_de_tiempo_en_pantalla los invalid son: 0
En la columna Estado_de_salud_mental los invalid son: 0
En la columna Nivel_de_estrÃ©s los invalid son: 0
En la columna Horas_de_sueÃ±o los invalid son: 0
En la columna Horas_de_actividad_fÃ­sica los invalid son: 0
En la columna Acceso_a_sistemas_de_soporte los invalid son: 0
En la columna Impacto_en_el_entorno_laboral los invalid son: 0

Remplazamos los espacios vacÃ­os.

In [81]:
#Cambiamos de objeto a float los datos numÃ©ricos, el cÃ³digo se salta los espacios vacÃ­os 
df2['Edad'] = pd.to_numeric(df2['Edad'], errors='coerce')
df2['Horas_de_uso _de_la_tecnologÃ­a'] = pd.to_numeric(df2['Horas_de_uso _de_la_tecnologÃ­a'], errors='coerce')
df2['Horas_de_uso_de_las_redes_sociales'] = pd.to_numeric(df2['Horas_de_uso_de_las_redes_sociales'], errors='coerce')
df2['Horas_de_sueÃ±o'] = pd.to_numeric(df2['Horas_de_sueÃ±o'], errors='coerce')
df2['Horas_de_actividad_fÃ­sica'] = pd.to_numeric(df2['Horas_de_actividad_fÃ­sica'], errors='coerce')
df2

,Usuario,Edad,GÃ©nero,Horas_de_uso _de_la_tecnologÃ­a,Horas_de_uso_de_las_redes_sociales,Horas_de_juego,Horas_de_tiempo_en_pantalla,Estado_de_salud_mental,Nivel_de_estrÃ©s,Horas_de_sueÃ±o,Horas_de_actividad_fÃ­sica,Acceso_a_sistemas_de_soporte,Impacto_en_el_entorno_laboral
0,USER-00001,23.0,Mujer,6.57,6.00,0.68,12.36,Buena,Bajo,8.01,6.71,No,Negativo
1,USER-00002,21.0,Hombre,3.01,2.57,3.74,7.61,Mala,Alto,7.28,5.88,Si,Positivo
2,USER-00003,51.0,Hombre,3.04,6.14,1.26,3.16,Neutral,Alto,8.04,9.81,No,Negativo
3,USER-00004,25.0,Mujer,3.84,4.48,2.59,13.08,Excelente,Medio,5.62,5.28,Si,Negativo
4,USER-00005,53.0,Hombre,1.20,0.56,0.29,12.63,Buena,Bajo,5.55,4.00,No,Positivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12513,USER-07314,30.0,Otro,3.13,5.66,0.11,1.74,Buena,Bajo,4.05,0.47,Si,Neutral
12515,USER-09553,53.0,Mujer,10.32,7.35,4.58,NaN,Neutral,Bajo,7.30,5.92,No,Negativo
12519,USER-01052,36.0,Otro,8.97,3.02,4.05,6.52,Buena,Medio,5.40,8.44,Si,Positivo
12523,USER-02010,25.0,Otro,3.82,3.71,3.61,6.57,Mala,Bajo,4.78,2.29,Si,Negativo
12527,USER-06331,35.0,Mujer,4.28,0.90,4.90,NaN,Neutral,Alto,8.51,0.41,Si,Neutral

In [82]:
df2.isnull().sum()

Usuario                                92
Edad                                  101
GÃ©nero                                 83
Horas_de_uso _de_la_tecnologÃ­a        102
Horas_de_uso_de_las_redes_sociales    102
Horas_de_juego                        281
Horas_de_tiempo_en_pantalla           291
Estado_de_salud_mental                 98
Nivel_de_estrÃ©s                       102
Horas_de_sueÃ±o                        110
Horas_de_actividad_fÃ­sica              95
Acceso_a_sistemas_de_soporte          114
Impacto_en_el_entorno_laboral         124
dtype: int64

In [83]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8905 entries, 0 to 12527
Data columns (total 13 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Usuario                             8813 non-null   object
 1   Edad                                8804 non-null   float64
 2   GÃ©nero                              8822 non-null   object
 3   Horas_de_uso _de_la_tecnologÃ­a      8803 non-null   float64
 4   Horas_de_uso_de_las_redes_sociales  8803 non-null   float64
 5   Horas_de_juego                      8624 non-null   float64
 6   Horas_de_tiempo_en_pantalla         8614 non-null   float64
 7   Estado_de_salud_mental              8807 non-null   object
 8   Nivel_de_estrÃ©s                     8803 non-null   object
 9   Horas_de_sueÃ±o                      8795 non-null   float64
 10  Horas_de_actividad_fÃ­sica           8810 non-null   float64
 11  Acceso_a_sistemas_de_soporte        8791 non-null   object
 12  Impacto_en_el_entorno_laboral       8781 non-null   object
dtypes: float64(7), object(6)
memory usage: 974.0+ KB

In [84]:
#Remplazamos los valores numÃ©ricos por su promedio.
df2['Edad'].fillna(df2['Edad'].mean(), inplace=True)
df2['Horas_de_uso _de_la_tecnologÃ­a'].fillna(df2['Horas_de_uso _de_la_tecnologÃ­a'].mean(), inplace=True)
df2['Horas_de_uso_de_las_redes_sociales'].fillna(df2['Horas_de_uso_de_las_redes_sociales'].mean(), inplace=True)
df2['Horas_de_sueÃ±o'].fillna(df2['Horas_de_sueÃ±o'].mean(), inplace=True)
df2['Horas_de_actividad_fÃ­sica'].fillna(df2['Horas_de_actividad_fÃ­sica'].mean(), inplace=True)
df2['Horas_de_juego'].fillna(df2['Horas_de_juego'].mean(), inplace=True)
df2['Horas_de_tiempo_en_pantalla'].fillna(df2['Horas_de_tiempo_en_pantalla'].mean(), inplace=True)
df2

C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\73393917.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Edad'].fillna(df2['Edad'].mean(), inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\73393917.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Horas_de_uso _de_la_tecnologÃ­a'].fillna(df2['Horas_de_uso _de_la_tecnologÃ­a'].mean(), inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\73393917.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Horas_de_uso_de_las_redes_sociales'].fillna(df2['Horas_de_uso_de_las_redes_sociales'].mean(), inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\73393917.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Horas_de_sueÃ±o'].fillna(df2['Horas_de_sueÃ±o'].mean(), inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\73393917.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Horas_de_actividad_fÃ­sica'].fillna(df2['Horas_de_actividad_fÃ­sica'].mean(), inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\73393917.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Horas_de_juego'].fillna(df2['Horas_de_juego'].mean(), inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\73393917.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Horas_de_tiempo_en_pantalla'].fillna(df2['Horas_de_tiempo_en_pantalla'].mean(), inplace=True)

,Usuario,Edad,GÃ©nero,Horas_de_uso _de_la_tecnologÃ­a,Horas_de_uso_de_las_redes_sociales,Horas_de_juego,Horas_de_tiempo_en_pantalla,Estado_de_salud_mental,Nivel_de_estrÃ©s,Horas_de_sueÃ±o,Horas_de_actividad_fÃ­sica,Acceso_a_sistemas_de_soporte,Impacto_en_el_entorno_laboral
0,USER-00001,23.0,Mujer,6.57,6.00,0.68,12.36000,Buena,Bajo,8.01,6.71,No,Negativo
1,USER-00002,21.0,Hombre,3.01,2.57,3.74,7.61000,Mala,Alto,7.28,5.88,Si,Positivo
2,USER-00003,51.0,Hombre,3.04,6.14,1.26,3.16000,Neutral,Alto,8.04,9.81,No,Negativo
3,USER-00004,25.0,Mujer,3.84,4.48,2.59,13.08000,Excelente,Medio,5.62,5.28,Si,Negativo
4,USER-00005,53.0,Hombre,1.20,0.56,0.29,12.63000,Buena,Bajo,5.55,4.00,No,Positivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12513,USER-07314,30.0,Otro,3.13,5.66,0.11,1.74000,Buena,Bajo,4.05,0.47,Si,Neutral
12515,USER-09553,53.0,Mujer,10.32,7.35,4.58,7.97265,Neutral,Bajo,7.30,5.92,No,Negativo
12519,USER-01052,36.0,Otro,8.97,3.02,4.05,6.52000,Buena,Medio,5.40,8.44,Si,Positivo
12523,USER-02010,25.0,Otro,3.82,3.71,3.61,6.57000,Mala,Bajo,4.78,2.29,Si,Negativo
12527,USER-06331,35.0,Mujer,4.28,0.90,4.90,7.97265,Neutral,Alto,8.51,0.41,Si,Neutral

In [85]:
#Elimino esta columna  Usuario porque no aporta nada a la investigaciÃ³n. 
df3=df2.drop(columns=['Usuario'])
df3

,Edad,GÃ©nero,Horas_de_uso _de_la_tecnologÃ­a,Horas_de_uso_de_las_redes_sociales,Horas_de_juego,Horas_de_tiempo_en_pantalla,Estado_de_salud_mental,Nivel_de_estrÃ©s,Horas_de_sueÃ±o,Horas_de_actividad_fÃ­sica,Acceso_a_sistemas_de_soporte,Impacto_en_el_entorno_laboral
0,23.0,Mujer,6.57,6.00,0.68,12.36000,Buena,Bajo,8.01,6.71,No,Negativo
1,21.0,Hombre,3.01,2.57,3.74,7.61000,Mala,Alto,7.28,5.88,Si,Positivo
2,51.0,Hombre,3.04,6.14,1.26,3.16000,Neutral,Alto,8.04,9.81,No,Negativo
3,25.0,Mujer,3.84,4.48,2.59,13.08000,Excelente,Medio,5.62,5.28,Si,Negativo
4,53.0,Hombre,1.20,0.56,0.29,12.63000,Buena,Bajo,5.55,4.00,No,Positivo
...,...,...,...,...,...,...,...,...,...,...,...,...
12513,30.0,Otro,3.13,5.66,0.11,1.74000,Buena,Bajo,4.05,0.47,Si,Neutral
12515,53.0,Mujer,10.32,7.35,4.58,7.97265,Neutral,Bajo,7.30,5.92,No,Negativo
12519,36.0,Otro,8.97,3.02,4.05,6.52000,Buena,Medio,5.40,8.44,Si,Positivo
12523,25.0,Otro,3.82,3.71,3.61,6.57000,Mala,Bajo,4.78,2.29,Si,Negativo
12527,35.0,Mujer,4.28,0.90,4.90,7.97265,Neutral,Alto,8.51,0.41,Si,Neutral

In [86]:
#Remplazamos espacios vacÃ­os de las columnas tipo objeto, por datos "Neutrales".
df3['GÃ©nero'].fillna("Otro", inplace=True)
df3['Estado_de_salud_mental'].fillna("Neutral", inplace=True)
df3['Nivel_de_estrÃ©s'].fillna("Medio", inplace=True)
df3['Impacto_en_el_entorno_laboral'].fillna("Neutral", inplace=True)

C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\3051069548.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['GÃ©nero'].fillna("Otro", inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\3051069548.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['Estado_de_salud_mental'].fillna("Neutral", inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\3051069548.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['Nivel_de_estrÃ©s'].fillna("Medio", inplace=True)
C:\Users\Gabriela\AppData\Local\Temp\ipykernel_6288\3051069548.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['Impacto_en_el_entorno_laboral'].fillna("Neutral", inplace=True)

In [87]:
df3.isnull().sum()

Edad                                    0
GÃ©nero                                  0
Horas_de_uso _de_la_tecnologÃ­a          0
Horas_de_uso_de_las_redes_sociales      0
Horas_de_juego                          0
Horas_de_tiempo_en_pantalla             0
Estado_de_salud_mental                  0
Nivel_de_estrÃ©s                         0
Horas_de_sueÃ±o                          0
Horas_de_actividad_fÃ­sica               0
Acceso_a_sistemas_de_soporte          114
Impacto_en_el_entorno_laboral           0
dtype: int64

In [88]:
#Elimino los NaN restantes, son de la columna 'Acceso_a_sistemas_de_soporte' y no pueden ser rellenados porque solo hay datos de sÃ­ y no. 
df4=df3.dropna()

In [89]:
df4.isnull().sum()

Edad                                  0
GÃ©nero                                0
Horas_de_uso _de_la_tecnologÃ­a        0
Horas_de_uso_de_las_redes_sociales    0
Horas_de_juego                        0
Horas_de_tiempo_en_pantalla           0
Estado_de_salud_mental                0
Nivel_de_estrÃ©s                       0
Horas_de_sueÃ±o                        0
Horas_de_actividad_fÃ­sica             0
Acceso_a_sistemas_de_soporte          0
Impacto_en_el_entorno_laboral         0
dtype: int64

In [90]:
df4 = df4.reset_index(drop=True)

In [101]:
#Cambiamos a entero
df4['Edad']=df4['Edad'].astype(int)

In [102]:
#Todos los datos tienen su tipo correcto
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8791 entries, 0 to 8790
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Edad                                8791 non-null   int64
 1   GÃ©nero                              8791 non-null   object
 2   Horas_de_uso _de_la_tecnologÃ­a      8791 non-null   float64
 3   Horas_de_uso_de_las_redes_sociales  8791 non-null   float64
 4   Horas_de_juego                      8791 non-null   float64
 5   Horas_de_tiempo_en_pantalla         8791 non-null   float64
 6   Estado_de_salud_mental              8791 non-null   object
 7   Nivel_de_estrÃ©s                     8791 non-null   object
 8   Horas_de_sueÃ±o                      8791 non-null   float64
 9   Horas_de_actividad_fÃ­sica           8791 non-null   float64
 10  Acceso_a_sistemas_de_soporte        8791 non-null   object
 11  Impacto_en_el_entorno_laboral       8791 non-null   object
dtypes: float64(6), int64(1), object(5)
memory usage: 824.3+ KB

In [93]:
df4.describe()

,Edad,Horas_de_uso _de_la_tecnologÃ­a,Horas_de_uso_de_las_redes_sociales,Horas_de_juego,Horas_de_tiempo_en_pantalla,Horas_de_sueÃ±o,Horas_de_actividad_fÃ­sica
count,8791.000000,8791.000000,8791.000000,8791.000000,8791.000000,8791.000000,8791.000000
mean,41.448868,6.438605,3.971663,2.529769,7.972097,6.492429,5.001663
std,13.805403,3.133297,2.295750,1.420544,3.968671,1.439642,2.880941
min,18.000000,1.000000,0.000000,0.000000,1.000000,4.000000,0.000000
25%,29.000000,3.780000,2.010000,1.335000,4.640000,5.270000,2.520000
50%,41.000000,6.444082,3.973487,2.529028,7.972650,6.493213,5.004032
75%,53.000000,9.080000,5.970000,3.760000,11.300000,7.730000,7.515000
max,65.000000,12.000000,8.000000,5.000000,15.000000,9.000000,10.000000

In [104]:
#Calcular el porcentaje de valores faltantes final por columna. 
df4.isnull().mean()*100

Edad                                  0.0
GÃ©nero                                0.0
Horas_de_uso _de_la_tecnologÃ­a        0.0
Horas_de_uso_de_las_redes_sociales    0.0
Horas_de_juego                        0.0
Horas_de_tiempo_en_pantalla           0.0
Estado_de_salud_mental                0.0
Nivel_de_estrÃ©s                       0.0
Horas_de_sueÃ±o                        0.0
Horas_de_actividad_fÃ­sica             0.0
Acceso_a_sistemas_de_soporte          0.0
Impacto_en_el_entorno_laboral         0.0
dtype: float64

In [105]:
df4.isnull().sum()

Edad                                  0
GÃ©nero                                0
Horas_de_uso _de_la_tecnologÃ­a        0
Horas_de_uso_de_las_redes_sociales    0
Horas_de_juego                        0
Horas_de_tiempo_en_pantalla           0
Estado_de_salud_mental                0
Nivel_de_estrÃ©s                       0
Horas_de_sueÃ±o                        0
Horas_de_actividad_fÃ­sica             0
Acceso_a_sistemas_de_soporte          0
Impacto_en_el_entorno_laboral         0
dtype: int64

In [107]:
#Buscar duplicados finales
df4.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8786    False
8787    False
8788    False
8789    False
8790    False
Length: 8791, dtype: bool

In [95]:
#Guardar los resultados en un csv
df4.to_csv("Base_limpia_proyecto.csv", index=True)